FROM docker.io/library/buntu: 18.04
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-8-jdk wget
RUN mkdir /us/local/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
/tmp/apache-tomcat-9.0.68.tar.gz
RUN cd /mp && tar xviz apache-tomcat-9.0.68.tar.gz
RUN cp -Rv/tmp/apache-tomcat-9.0.68/* /usr/local/tomcat/
ADD **/*.war /us/local/tomcat/webapps
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run